services:
  minecraft:
    image: recfortech/minecraft-world
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      ONLINE_MODE: "FALSE"
    volumes:
      # Assign directory 'data' to the container's /data path
      - ./data:/data
    # Restart policy
    restart: on-failure:5
    # The docker networks configuration for the minecraft service
    networks:
      # The name of the network to put the minecraft service into
      minecraft:
        # A network alias within the docker network to give the minecraft service
        aliases:
          - minecraft
  prometheus:
    image: prom/prometheus
    tty: true
    stdin_open: true
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    stdin_open: true
    ports:
      - "3000:3000"

# Docker network configurations
networks:
  # The network to configure
  minecraft:
    # The minecraft network will be created if it does not exist
    name: minecraft
