services:
  minecraft:
    image: recfortech/minecraft-world
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    environment:
      TYPE: AUTO_CURSEFORGE
      CF_API_KEY: $$2a$$10$$gYA2Wi9Ir.GjSNyT0G1j7e.KTUjHv3OzTxjPAyVRgVrwdm47WT2uS
      CF_PAGE_URL: https://www.curseforge.com/minecraft/modpacks/all-the-mods-8
      EULA: "TRUE"
      ONLINE_MODE: "FALSE"
      MEMORY: 4G
    volumes:
      # Assign directory 'data' to the container's /data path
      - L:\Minecraft Docker Server\mc-data:/data
    # Restart policy
    restart: on-failure:5
    # The docker networks configuration for the minecraft service
    networks:
      # The name of the network to put the minecraft service into
      minecraft:
        # A network alias within the docker network to give the minecraft service
        aliases:
          - minecraft
  prometheus:
    image: prom/prometheus
    tty: true
    stdin_open: true
    ports:
      - "9090:9090"
    # Restart policy
    restart: on-failure:5
    networks:
      minecraft:
        aliases:
          - prometheus
  grafana:
    image: grafana/grafana
    stdin_open: true
    ports:
      - "3000:3000"
    # Restart policy
    restart: on-failure:5
    networks:
      minecraft:
        aliases:
          - grafana

# Docker network configurations
networks:
  # The network to configure
  minecraft:
    # The minecraft network will be created if it does not exist
    name: minecraft
